// get products 
export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const MEN_PRODUCT_SUCCESS = "MEN_PRODUCT_SUCCESS"
export const WOMEN_PRODUCT_SUCCESS = "WOMEN_PRODUCT_SUCCESS"
export const PRODUCT_FAILURE = "PRODUCT_FAILURE"
export const POST_TO_CART ="POST_TO_CART";